sudo: true

language: python

python:
  - "3.7"

dist: xenial  # for python 3.7

install:
  - pip install -r requirements.txt

script:
  - cd test
  - python3 Test_unittest.py
  - python3 Test_doctest.py

notifications:
  email:
    on_success: never
    on_failure: change
