# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\youtube_player\ui\you_viewer_v1.0.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 635)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(800, 635))
        MainWindow.setMaximumSize(QtCore.QSize(800, 635))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("resource/title.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 291, 371))
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 20, 271, 111))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("./resource/logo.png"))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.loginBtn = QtWidgets.QPushButton(self.groupBox)
        self.loginBtn.setGeometry(QtCore.QRect(10, 140, 271, 31))
        self.loginBtn.setObjectName("loginBtn")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.groupBox)
        self.calendarWidget.setGeometry(QtCore.QRect(10, 180, 271, 183))
        self.calendarWidget.setObjectName("calendarWidget")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(310, 9, 481, 371))
        self.groupBox_2.setObjectName("groupBox_2")
        self.webView = QtWebEngineWidgets.QWebEngineView(self.groupBox_2)
        self.webView.setGeometry(QtCore.QRect(10, 20, 461, 341))
        self.webView.setUrl(QtCore.QUrl("about:blank"))
        self.webView.setObjectName("webView")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(10, 375, 781, 31))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 399, 381, 161))
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        self.label_4.setGeometry(QtCore.QRect(10, 30, 61, 21))
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        self.label_5.setGeometry(QtCore.QRect(10, 54, 61, 31))
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setGeometry(QtCore.QRect(10, 84, 61, 31))
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.urlLE = QtWidgets.QLineEdit(self.groupBox_3)
        self.urlLE.setGeometry(QtCore.QRect(80, 30, 221, 21))
        self.urlLE.setObjectName("urlLE")
        self.previewBtn = QtWidgets.QPushButton(self.groupBox_3)
        self.previewBtn.setGeometry(QtCore.QRect(310, 30, 61, 21))
        self.previewBtn.setObjectName("previewBtn")
        self.pathLE = QtWidgets.QLineEdit(self.groupBox_3)
        self.pathLE.setGeometry(QtCore.QRect(80, 60, 221, 21))
        self.pathLE.setObjectName("pathLE")
        self.pathLE.setReadOnly(True)
        self.fileNavBtn = QtWidgets.QToolButton(self.groupBox_3)
        self.fileNavBtn.setGeometry(QtCore.QRect(310, 60, 61, 21))
        self.fileNavBtn.setObjectName("fileNavBtn")
        self.qualityCB = QtWidgets.QComboBox(self.groupBox_3)
        self.qualityCB.setGeometry(QtCore.QRect(80, 90, 291, 22))
        self.qualityCB.setObjectName("qualityCB")
        self.endBtn = QtWidgets.QPushButton(self.groupBox_3)
        self.endBtn.setGeometry(QtCore.QRect(310, 120, 61, 31))
        self.endBtn.setObjectName("endBtn")
        self.startBtn = QtWidgets.QPushButton(self.groupBox_3)
        self.startBtn.setGeometry(QtCore.QRect(240, 120, 61, 31))
        self.startBtn.setObjectName("startBtn")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(400, 400, 391, 161))
        self.groupBox_4.setObjectName("groupBox_4")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.groupBox_4)
        self.plainTextEdit.setGeometry(QtCore.QRect(10, 20, 371, 131))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.plainTextEdit.setReadOnly(True)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(10, 556, 781, 31))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 580, 81, 21))
        self.label_2.setObjectName("label_2")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(90, 580, 20, 21))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(110, 580, 281, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(400, 580, 91, 21))
        self.label_3.setObjectName("label_3")
        self.progressBar_2 = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar_2.setGeometry(QtCore.QRect(510, 580, 281, 23))
        self.progressBar_2.setProperty("value", 0)
        self.progressBar_2.setObjectName("progressBar_2")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(490, 580, 20, 21))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Information"))
        self.loginBtn.setText(_translate("MainWindow", "Authentication"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Preview"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Download URL & Save Location"))
        self.label_4.setText(_translate("MainWindow", "Video URL :"))
        self.label_5.setText(_translate("MainWindow", "Save To :"))
        self.label_6.setText(_translate("MainWindow", "Quality :"))
        self.previewBtn.setText(_translate("MainWindow", "OK"))
        self.fileNavBtn.setText(_translate("MainWindow", "..."))
        self.endBtn.setText(_translate("MainWindow", "End"))
        self.startBtn.setText(_translate("MainWindow", "Start"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Log"))
        self.label_2.setText(_translate("MainWindow", "Browser Loading"))
        self.label_3.setText(_translate("MainWindow", "Download Loading"))

from PyQt5 import QtWebEngineWidgets


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
